name: flutter_video_compressor
description: A Flutter plugin that provides video, image, and audio compression capabilities using native compression algorithms from the React Native Compressor library.
version: 1.0.0
homepage: https://github.com/turanoz/flutter_video_compressor
repository: https://github.com/turanoz/flutter_video_compressor
issue_tracker: https://github.com/turanoz/flutter_video_compressor/issues
documentation: https://github.com/turanoz/flutter_video_compressor#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # This section identifies this package as a plugin package.
  plugin:
    platforms:
      android:
        package: com.videocompressor.flutter_video_compressor
        pluginClass: CompressorPlugin
      ios:
        pluginClass: CompressorPlugin
